cmake_minimum_required(VERSION 3.14)
project(hmx_load_calibration C)
set(CMAKE_C_STANDARD 11)
include(${HEXAGON_SDK_ROOT}/build/cmake/hexagon_fun.cmake)
include_directories(${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_BINARY_DIR}
    ${HEXAGON_SDK_ROOT}/incs ${HEXAGON_SDK_ROOT}/incs/stddef ${HEXAGON_SDK_ROOT}/rtos/qurt)
if(OS_TYPE MATCHES "HLOS")
    add_library(hmx_load_calibration SHARED ${CMAKE_CURRENT_BINARY_DIR}/hmx_load_calibration_stub.c)
    build_idl(hmx_load_calibration.idl hmx_load_calibration)
    choose_dsprpc(${DSP_TYPE} dsprpc)
    link_custom_library(hmx_load_calibration ${dsprpc})
    add_executable(hmx_load_calibration_test host.c)
    set_common_compile_and_link_options(hmx_load_calibration_test)
    target_compile_options(hmx_load_calibration_test PRIVATE -Wall -Wextra)
    target_link_libraries(hmx_load_calibration_test hmx_load_calibration m)
    copy_binaries(hmx_load_calibration hmx_load_calibration_test)
else()
    add_library(hmx_load_calibration_skel SHARED ${CMAKE_CURRENT_BINARY_DIR}/hmx_load_calibration_skel.c dsp.c hvx_kernel.c)
    build_idl(hmx_load_calibration.idl hmx_load_calibration_skel)
    set_source_files_properties(dsp.c PROPERTIES COMPILE_OPTIONS "-mno-hvx;-mhmx;-fno-vectorize;-fno-slp-vectorize")
    set_source_files_properties(hvx_kernel.c PROPERTIES COMPILE_OPTIONS "-mhvx;-mhvx-length=128B;-fno-vectorize;-fno-slp-vectorize")
    copy_binaries(hmx_load_calibration_skel)
endif()
